pictures_downloader:
  credentials_path: "credentials/credentials.json"
  pictures_path: "pictures"

face_detection:
  model_path: "model"
  model_url:
    [
      "https://raw.githubusercontent.com/opencv/opencv_3rdparty/dnn_samples_face_detector_20180220_uint8/opencv_face_detector_uint8.pb",
      "https://raw.githubusercontent.com/opencv/opencv/master/samples/dnn/face_detector/opencv_face_detector.pbtxt",
    ]
  pad: 15

image_processing:
  max_size: 448
  trim_initial_variance: 250
  trim_delta_variance: 25
  trim_min_area_pct: .25

image_vectorizer:
  file_list_path: "model/file_list.txt"
  vectors_path: "model/vectors.npy"

ann_config:
  ann_model_path: "model/ann_model.hsnw"
  init:
    method: "hnsw"
    space: "cosinesimil"
    data_type: nmslib.DataType.DENSE_VECTOR
  index_time":
    M: 15
    indexThreadQty: 4
    efConstruction: 100
  query_time":
    efSearch": 100
